source ~/.gitshell-config.sh
source ~/.git-prompt.sh
source ~/.colors.sh

PROMPT_COMMAND='__git_ps1 "\[$BWhite\]______________________________________________________________________________________________________________\n\n\[$BGreen\]\u\[$BWhite\] at \[$BBlue\]\h\[$BWhite\] in \[$BCyan\]\w\[$BPurple\]" "\n\[$BRed\]#!\[$BWhite\] "'
PS2="\[$BRed\][...] \[$BWhite\] "

alias less='less -r'
alias ls='ls -lFhq --color=always'
